version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flea-market-app
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - flea-net

  nginx:
    image: nginx:1.21.1
    container_name: flea-nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - flea-net

  db:
    image: mysql:8.0
    container_name: flea-market-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - flea-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin     # ← 正しい phpMyAdmin イメージ
    container_name: flea-market-pma  # ← 一意な名前に変更
    environment:
      PMA_HOST: db                   # ← dbサービス名に接続
      PMA_USER: laravel_user
      PMA_PASSWORD: secret
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - flea-net

volumes:
  dbdata:

networks:
  flea-net:
    driver: bridge
